config/routes.rb
Rails.application.routes.draw do
  
  get 'searches/index'

  get 'welcome/index'

  root 'welcome#index'
  
  
  get 'searches/create'
  

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @search = Search.new
  end
  
  def create
    @who = params[:search][:who]
    #redirect_to root_path
    render 'edit'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="description" content="これからのテンプレートは目的に応じて選ぶ時代へ。あなたの目的を達成できるテンプレートがここにある。">
  <title>THE TEMPLATE | 世界一簡単に選べるテンプレートサイト</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= yield %>
</html>

app/views/searches/edit.html.erb
<%= @who %>

app/views/searches/index.html.erb
<body class="search_page">
    <header>
        <h2><%= image_tag 'title.png' %></h2>
    </header>
    <div id="container">
        <h1>テンプレート検索</h1>
        <p>
        ついつい見た目で選んでしまい、結果的に成果が出ない…ということを体験したことはないでしょうか？きっと多くの人が体験したことがあるこの問題を解決するのが、目的達成を軸に自動でテンプレートを選んでくれるこのサービス。カラーリングもターゲットユーザーに応じて自動設定します。
        </p>
        <%= form_for @search, url: searches_create_path, html: {method: "get"} do |f| %>
        <div class="who">
            <h3>目的</h3>
            <p><%= f.select :who, [["就職活動のために", "就職活動"], ["カフェ店舗告知のために", "店舗告知"]] %></p>
        </div>
        <div class="what">
            <h3>何を</h3>
            <p><%= f.select :what, [["あああ", "rails_base"], ["Rubyの基礎", "ruby_base"]] %></p>
        </div>
        <div class="how">
            <h3>どんな風に？</h3>
            <p><%= f.select :how, [["Railsの基礎", "rails_base"], ["Rubyの基礎", "ruby_base"]] %></p>
        </div>
        <div class="go_contents">
            <%= f.submit "検索する", data: { disable_with: "検索中..." } %>
        </div>
        <% end %>
    </div>
</body>

app/views/welcome/index.html.erb
<body class="welcome_page">
    <header>
        <h2><%= image_tag 'title.png' %></h2>
    </header>
    <div id="container">
        <%= @test %>
        <h1>HTMLが分かるあなたへ<br>成果を出せる自動選択！</h1>
        <p>
        ついつい見た目で選んでしまい、結果的に成果が出ない…ということを体験したことはないでしょうか？きっと多くの人が体験したことがあるこの問題を解決するのが、目的達成を軸に自動でテンプレートを選んでくれるこのサービス。カラーリングもターゲットユーザーに応じて自動設定します。
        </p>
        <div class="go_contents">
            <%= link_to "はじめましょう", :controller => "searches" %>
        </div>
    </div>
</body>